# Generated by Django 5.0.1 on 2024-02-04 20:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'pharmacy_document_type',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('ruc', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'pharmacy_provider',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('series', models.CharField(max_length=500)),
                ('number', models.CharField(max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('igv', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.documenttype')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.provider')),
            ],
            options={
                'db_table': 'pharmacy_purchase',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase')),
            ],
            options={
                'db_table': 'pharmacy_purchase_detail',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='details',
            field=models.ManyToManyField(through='purchases.PurchaseDetail', to='inventory.product'),
        ),
        migrations.AddConstraint(
            model_name='purchasedetail',
            constraint=models.UniqueConstraint(fields=('purchase', 'product'), name='unique_purchase_detail'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('series', 'number', 'provider'), name='unique_purchase'),
        ),
    ]
