# Generated by Django 5.0.1 on 2024-02-04 20:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'pharmacy_generic',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=35)),
                ('representative', models.CharField(blank=True, max_length=50)),
                ('observations', models.TextField(blank=True, max_length=500)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pharmacy_laboratory',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'pharmacy_presentation',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_stock', models.PositiveIntegerField()),
                ('indications', models.TextField(blank=True, max_length=500)),
                ('generic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.generic')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.laboratory')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.presentation')),
            ],
            options={
                'db_table': 'pharmacy_product',
            },
        ),
    ]
