# Generated by Django 5.0.1 on 2024-02-04 20:29

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=100)),
                ('serie', models.PositiveIntegerField()),
                ('numero', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.documenttype')),
            ],
            options={
                'db_table': 'pharmacy_sale',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
            ],
            options={
                'db_table': 'pharmacy_sale_detail',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='details',
            field=models.ManyToManyField(through='sales.SaleDetail', to='inventory.product'),
        ),
        migrations.AddConstraint(
            model_name='saledetail',
            constraint=models.UniqueConstraint(fields=('sale', 'product'), name='unique_sale_detail'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('serie', 'numero'), name='unique_sale'),
        ),
    ]
